services:
    LAG\SmokerBundle\Response\Handler\ResponseCodeHandler:
        class: LAG\SmokerBundle\Response\Handler\ResponseCodeHandler
        arguments:
            - '%lag_smoker.routes%'

    LAG\SmokerBundle\Response\Handler\ResponseHandlerInterface: '@LAG\SmokerBundle\Response\Handler\ResponseCodeHandler'

    LAG\SmokerBundle\Response\Handler\HtmlHandler:
        class: LAG\SmokerBundle\Response\Handler\HtmlHandler
        arguments:
            - '@LAG\SmokerBundle\Url\Requirements\Mapping\MappingResolverInterface'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '%lag_smoker.routes%'
