services:
    LAG\SmokerBundle\Response\Handler\ResponseCodeHandler:
        class: LAG\SmokerBundle\Response\Handler\ResponseCodeHandler
        arguments:
            - '%lag_smoker.routes%'

    LAG\SmokerBundle\Response\Handler\ResponseHandlerInterface: '@LAG\SmokerBundle\Response\Handler\ResponseCodeHandler'
