services:
    LAG\SmokerBundle\Url\Provider\SymfonyUrlProvider:
        class: LAG\SmokerBundle\Url\Provider\SymfonyUrlProvider
        arguments:
            - '%lag_smoker.routing%'
            - '%lag_smoker.routes%'
            - '%lag_smoker.mapping%'
            - '@router'
            - '@LAG\SmokerBundle\Url\Requirements\Registry\RequirementsProviderRegistry'

    LAG\SmokerBundle\Url\Provider\UrlProviderInterface: '@LAG\SmokerBundle\Url\Provider\SymfonyRoutingProvider'

    LAG\SmokerBundle\Bridge\Doctrine\ORM\RequirementsProvider\DoctrineRequirementsProvider:
        class: LAG\SmokerBundle\Bridge\Doctrine\ORM\RequirementsProvider\DoctrineRequirementsProvider
        arguments:
            - '@LAG\SmokerBundle\Url\Requirements\Mapping\MappingResolverInterface'
            - '@Symfony\Component\Routing\RouterInterface'
            - '@LAG\SmokerBundle\Bridge\Doctrine\ORM\DataProvider\DoctrineDataProvider'


    LAG\SmokerBundle\Bridge\Doctrine\ORM\DataProvider\DoctrineDataProvider:
        class: LAG\SmokerBundle\Bridge\Doctrine\ORM\DataProvider\DoctrineDataProvider
        arguments:
            - '@doctrine.orm.entity_manager'

    LAG\SmokerBundle\Url\Requirements\Provider\RequirementsProviderInterface: '@LAG\SmokerBundle\Bridge\Doctrine\ORM\RequirementsProvider\DoctrineRequirementsProvider'
