services:
    LAG\SmokerBundle\Url\Requirements\Mapping\MappingResolver:
        class: LAG\SmokerBundle\Url\Requirements\Mapping\MappingResolver
        arguments:
            - '%lag_smoker.mapping%'

    LAG\SmokerBundle\Contracts\Requirements\Mapping\MappingResolverInterface: '@LAG\SmokerBundle\Url\Requirements\Mapping\MappingResolver'
