services:
    ### Console commands ###
    LAG\SmokerBundle\Command\GenerateCacheCommand:
        class: LAG\SmokerBundle\Command\GenerateCacheCommand
        arguments:
            - '%kernel.cache_dir%'
            - '@LAG\SmokerBundle\Url\Registry\UrlProviderRegistry'
        tags:
            - {name: console.command}

    LAG\SmokerBundle\Command\SmokeCommand:
        class: LAG\SmokerBundle\Command\SmokeCommand
        arguments:
            - '%kernel.cache_dir%'
            - '@LAG\SmokerBundle\Response\Registry\ResponseHandlerRegistry'
            - '@router'
            - '@twig'
        tags:
            - {name: console.command}
    ########################

    ### Providers ###
    LAG\SmokerBundle\Url\Provider\RoutingUrlProvider:
        class: LAG\SmokerBundle\Url\Provider\RoutingUrlProvider
        arguments:
            - '@router'
            - '@LAG\SmokerBundle\Requirements\Registry\RequirementsProviderRegistry'

    LAG\SmokerBundle\Requirements\Provider\RequirementsProvider:
        class: LAG\SmokerBundle\Requirements\Provider\RequirementsProvider
        arguments:
            - '%jk_smoker.mapping%'
            - '@router'
            - '@doctrine'
    #################

    ### Registries ###
    LAG\SmokerBundle\Requirements\Registry\RequirementsProviderRegistry:
        class: LAG\SmokerBundle\Requirements\Registry\RequirementsProviderRegistry
        calls:
            - ['add', ['default', '@LAG\SmokerBundle\Requirements\Provider\RequirementsProvider']]

    LAG\SmokerBundle\Response\Registry\ResponseHandlerRegistry:
        class: LAG\SmokerBundle\Response\Registry\ResponseHandlerRegistry

    LAG\SmokerBundle\Url\Registry\UrlProviderRegistry:
        class: LAG\SmokerBundle\Url\Registry\UrlProviderRegistry
        calls:
            - ['add', ['default', '@LAG\SmokerBundle\Url\Provider\RoutingUrlProvider']]
    ##################

    ### Response handlers ###
    LAG\SmokerBundle\Response\Handler\SuccessResponseHandler:
        class: LAG\SmokerBundle\Response\Handler\SuccessResponseHandler
    #########################
